"""
Configuration package for DoomSat agent.
Centralizes all tunable parameters for easy adjustment and evolution.
"""

from .combat import *
from .navigation import *
from .defaults import *

__all__ = [
    # Combat parameters
    'COMBAT_BURST_MIN', 'COMBAT_BURST_MAX', 'COMBAT_BURST_DEFAULT',
    'COMBAT_COOLDOWN_MIN', 'COMBAT_COOLDOWN_MAX', 'COMBAT_COOLDOWN_DEFAULT',
    'COMBAT_REARM_DEFAULT',
    'COMBAT_STRAFE_SWITCH_MIN', 'COMBAT_STRAFE_SWITCH_MAX', 'COMBAT_STRAFE_SWITCH_DEFAULT',
    'COMBAT_MAX_ACTIVE_MIN', 'COMBAT_MAX_ACTIVE_MAX', 'COMBAT_MAX_ACTIVE_DEFAULT',
    'COMBAT_SEEN_TICKS_DEFAULT',
    'COMBAT_WALL_BRIGHTNESS_THRESHOLD',
    'COMBAT_WALL_VARIANCE_THRESHOLD',
    'COMBAT_AIM_THRESHOLD_WIDE',
    'COMBAT_AIM_THRESHOLD_NARROW',
    'COMBAT_CONFIDENCE_THRESHOLD',
    
    # Navigation parameters
    'NAV_NODE_VISIT_RADIUS_MIN', 'NAV_NODE_VISIT_RADIUS_MAX', 'NAV_NODE_VISIT_RADIUS_DEFAULT',
    'NAV_STUCK_RADIUS_MIN', 'NAV_STUCK_RADIUS_MAX', 'NAV_STUCK_RADIUS_DEFAULT',
    'NAV_STUCK_DIST_DELTA_DEFAULT',
    'NAV_STUCK_MIN_PROGRESS_DEFAULT',
    'NAV_STUCK_TIME_MIN', 'NAV_STUCK_TIME_MAX', 'NAV_STUCK_TIME_DEFAULT',
    'NAV_STUCK_WINDOW_DEFAULT',
    'NAV_EXIT_FORCE_DIST_DEFAULT',
    'NAV_END_SUBROUTE_BLOCK_DIST_MIN', 'NAV_END_SUBROUTE_BLOCK_DIST_MAX', 'NAV_END_SUBROUTE_BLOCK_DIST_DEFAULT',
    'NAV_ROUTE_TRACE_MAX_DEFAULT',
    'NAV_SUBROUTE_PAUSE_DURATION_DEFAULT',
    'NAV_SUBROUTE_COOLDOWN_DEFAULT',
    'NAV_USE_COOLDOWN_DEFAULT',
    'NAV_PATH_WAYPOINT_RADIUS',
    'NAV_ANGLE_FORWARD_THRESHOLD',
    'NAV_ANGLE_SHARP_TURN_THRESHOLD',
    'NAV_EXPLORE_COOLDOWN_DEFAULT',
    'NAV_EXIT_USE_BURST_DURATION',
    'NAV_EXIT_SIDE_SWAP_COOLDOWN',
    
    # Default game settings
    'DEFAULT_EPISODE_TIMEOUT',
    'DEFAULT_ACTION_FRAME_SKIP',
    'DEFAULT_STEP_DELAY',
    'DEFAULT_LOG_INTERVAL',
    'DEFAULT_HANG_TIMEOUT',
    'DEFAULT_HANG_ACTION_TIMEOUT',
    'DEFAULT_TICRATE',
    'DEFAULT_MAP_NAME',
    'DEFAULT_WAD_PATH',
    
    # Enemy detection
    'ENEMY_KEYWORDS',
    'ACTION_NAMES',
]
